#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/stat.h>
#include <sys/types.h>
#ifndef GLOBAL_H
#define GLOBAL_H
#include "main.h"
#include "../headers/Exercice2.h"
#include "../headers/Exercice3.h"
#include "../headers/exercice4.h"
#include "../headers/Exercice5.h"
